### PR TITLE
MAJOR: respect whitespaces

### PR DESCRIPTION
**Pull request by adrai**
alternative to: #45
should help to fix: https://github.com/i18next/react-i18next/pull/1283
originally from here: https://github.com/rayd/html-parse-stringify2/blob/master/lib/parse.js#L14

### CODE REVIEW

**Review by HenrikJoreteg — APPROVED** [review]
Looks good will merge then publish after a bit more local inspection. Thanks @adrai

**Comment by adrai** [comment]
I have to thank you 😉

**Comment by HenrikJoreteg** [comment]
Published to npm as `3.0.0`: https://www.npmjs.com/package/html-parse-stringify

**Comment by adrai** [comment]
Thank you @HenrikJoreteg!
@kachkaev do you want to update your PR?

**Pull request merged**
